# Generated by Django 6.1.1 on 2026-09-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_amenity_options_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.property'),
        ),
    ]
