# Generated by Django 6.1.1 on 2026-09-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_sellersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersubmission',
            name='image',
        ),
        migrations.CreateModel(
            name='SellerSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seller_submissions/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.sellersubmission')),
            ],
        ),
    ]
